<?php

namespace Batik\Traits\Tables;

Trait TableData {

    public function dataPaymentMethods() {
        return [
            [
                'type' => 'Admin_Only',
                'name' => 'Bank',
                'description' => null,
                'admin_name' => 'Bank',
                'admin_description' => 'Bank Draft',
                'slug' => 'bank',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => get_stylesheet_directory_uri() . '/assets/dist/images/bank.jpg',
                'scope' => serialize(['CART', 'ADMIN']),
            ],
            [
                'type' => 'Admin_Only',
                'name' => 'Cash',
                'description' => null,
                'admin_name' => 'Cash',
                'admin_description' => 'Cash Delivered Physically',
                'slug' => 'cash',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
            [
                'type' => 'Admin_Only',
                'name' => 'Check',
                'description' => null,
                'admin_name' => 'Check',
                'admin_description' => 'Paper Check',
                'slug' => 'check',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
            [
                'type' => 'Admin_Only',
                'name' => 'Credit Card',
                'description' => null,
                'admin_name' => 'Credit Card',
                'admin_description' => 'Offline Credit Card Payment',
                'slug' => 'creditcard',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
            [
                'type' => 'Admin_Only',
                'name' => 'Debit Card',
                'description' => null,
                'admin_name' => 'Debit Card',
                'admin_description' => 'Offline Debit Payment',
                'slug' => 'debitcard',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
            [
                'type' => 'Invoice',
                'name' => 'Invoice',
                'description' => 'After clicking &quot;Finalize Registration&quot;, you will be given instructions on how to access your invoice and complete your payment.<br />Please note that event spaces will not be reserved until payment is received in full, and any remaining tickets could be sold to others in the meantime.',
                'admin_name' => 'Invoice',
                'admin_description' => 'Invoice received with monies included',
                'slug' => 'invoice',
                'data_order' => 0,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
            [
                'type' => 'Admin_Only',
                'name' => 'Money Order',
                'description' => null,
                'admin_name' => 'Money Order',
                'admin_description' => null,
                'slug' => 'moneyorder',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
            [
                'type' => 'Admin_Only',
                'name' => 'Paypal',
                'description' => null,
                'admin_name' => 'Paypal',
                'admin_description' => 'Paypal eCheck, Inovice, etc',
                'slug' => 'paypal',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
            [
                'type' => 'Admin_Only',
                'name' => 'Other',
                'description' => null,
                'admin_name' => 'Other',
                'admin_description' => 'Other method of payment',
                'slug' => 'other',
                'data_order' => null,
                'debug_mode' => 0,
                'wp_user' => get_current_user_id(),
                'open_by_default' => 0,
                'button_url' => null,
                'scope' => serialize(['ADMIN']),
            ],
        ];
    }

    public function dataStatuses() {
        return [
            [
                'code' => 'ACT',
                'name' => 'ACTIVE',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'CLS',
                'name' => 'REGISTRATION_CLOSED',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'DEL',
                'name' => 'DELETED',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'DEN',
                'name' => 'DENIED',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'DRF',
                'name' => 'DRAFT',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'EDR',
                'name' => 'DRAFT',
                'type' => 'email',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'ESN',
                'name' => 'SENT',
                'type' => 'email',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'EXP',
                'name' => 'EXPIRED',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'MDO',
                'name' => 'DEBUG_ONLY',
                'type' => 'message',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'MEX',
                'name' => 'MESSENGER_EXECUTING',
                'type' => 'message',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'MFL',
                'name' => 'FAIL',
                'type' => 'message',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'MIC',
                'name' => 'FAIL',
                'type' => 'message',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'MID',
                'name' => 'IDLE',
                'type' => 'message',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'MRS',
                'name' => 'RESEND',
                'type' => 'message',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'MSN',
                'name' => 'SENT',
                'type' => 'message',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'NAC',
                'name' => 'NOT_ACTIVE',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'NOP',
                'name' => 'REGISTRATION_NOT_OPEN',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'ONG',
                'name' => 'ONGOING',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'OPN',
                'name' => 'REGISTRATION_OPEN',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'PAP',
                'name' => 'APPROVED',
                'type' => 'payment',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'PCN',
                'name' => 'CANCELLED',
                'type' => 'payment',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'PDC',
                'name' => 'DECLINED',
                'type' => 'payment',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'PFL',
                'name' => 'FAILED',
                'type' => 'payment',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'PND',
                'name' => 'PENDING',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'PPN',
                'name' => 'PENDING',
                'type' => 'payment',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'RAP',
                'name' => 'APPROVED',
                'type' => 'registration',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'RCN',
                'name' => 'CANCELLED',
                'type' => 'registration',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'RDC',
                'name' => 'DECLINED',
                'type' => 'registration',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'RIC',
                'name' => 'INCOMPLETE',
                'type' => 'registration',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'RNA',
                'name' => 'NOT_APPROVED',
                'type' => 'registration',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'RPP',
                'name' => 'PENDING_PAYMENT',
                'type' => 'registration',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'RWL',
                'name' => 'WAIT_LIST',
                'type' => 'registration',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'SEC',
                'name' => 'SECONDARY',
                'type' => 'event',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'TAB',
                'name' => 'ABANDONED',
                'type' => 'transaction',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'TCM',
                'name' => 'COMPLETE',
                'type' => 'transaction',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'TFL',
                'name' => 'FAILED',
                'type' => 'transaction',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 0,
            ],
            [
                'code' => 'TIN',
                'name' => 'INCOMPLETE',
                'type' => 'transaction',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
            [
                'code' => 'TOP',
                'name' => 'OVERPAID',
                'type' => 'transaction',
                'can_edit' => 0,
                'description' => null,
                'is_open' => 1,
            ],
        ];
    }
}