<?php
return [
	'event' => [
		'slug' => 'event',
		'singular' => 'Event',
		'plural' => 'Events',
		'menu_icon' => 'dashicons-calendar-alt',
		'menu_position' => 18,
		'text_domain' => 'batik',
		'description' => 'Wahaha event list',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => true,
		'capability_type' => 'post',
		'has_archive' => true,
		'hierarchical' => true,
		'show_in_rest' => true,
	],
	'room' => [
		'slug' => 'room',
		'singular' => 'Karaoke Room',
		'plural' => 'Karaoke Rooms',
		'menu_icon' => 'dashicons-store',
		'menu_position' => 18,
		'text_domain' => 'batik',
		'description' => 'Wahaha karaoke room list',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => true,
		'capability_type' => 'post',
		'has_archive' => true,
		'hierarchical' => false,
		'show_in_rest' => true,
	],
	'hotel' => [
		'slug' => 'hotel-room',
		'singular' => 'Hotel Room',
		'plural' => 'Hotel Rooms',
		'menu_icon' => 'dashicons-building',
		'menu_position' => 18,
		'text_domain' => 'batik',
		'description' => 'Wahaha hotel room list',
		'public' => false,
		'publicly_queryable' => false,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => false,
		'capability_type' => 'post',
		'has_archive' => false,
		'hierarchical' => false,
		'show_in_rest' => true,
	],
	'lounge' => [
		'slug' => 'lounge',
		'singular' => 'Lounge',
		'plural' => 'Lounges',
		'menu_icon' => 'dashicons-buddicons-tracking',
		'menu_position' => 18,
		'text_domain' => 'batik',
		'description' => 'Wahaha lounge & bar',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => false,
		'capability_type' => 'post',
		'has_archive' => false,
		'hierarchical' => false,
		'show_in_rest' => false,
	],
];